### ISSUE TITLE
Extending / adding new behaviours.....

### ISSUE THREAD

**Issue by natiki** [tSQLt-org/tSQLt#30]
Hi,

I am investigating the framework as a means to test some database code. Unless I have misunderstood things there seems to be a direct correlation between the number of stored procedures "test methods" that would need to be written when say:

1. You want to test a combination of parameters. 

For instance there is no ability to pass parameters to tSQLt.Run(). So if I have a SP that has a single param that I want to test with 3 separate values I would need THREE stored procedure test methods. As opposed to what can be done with NUnit say. See this [SO](https://stackoverflow.com/questions/47885513/any-solutions-to-getting-nunit-style-testcase-functionality-in-tsqlt) post for an example.

2) Test all the result sets returned by a stored procedure

This requires multiple calls to the underlying SP so that we can call http://tsqlt.org/201/using-tsqlt-resultsetfilter/ with the appropriate offset.

That all being said.... What options are there for extending the framework? While I see that we have a CLR available to us there is no clear indication of:

a) What the extension points are
b) Whether this project [is actually still alive](https://github.com/tSQLt-org/tSQLt/issues/29) and improving with the last release being at the beginning of 2016

Any feedback greatly appreciated.

**Comment by mbt1** [comment]
Please ask questions like this on StackOverflow using the tSQLt tag. That way other tSQLt users will be able to find them and benefit from them. After all, this is a how-to question, not an issue.

That being said, let's look at your specific case.
tSQLt allows the use of stored procedures that are not test cases within test classes. So to achieve, what you are looking for, I usually create a stored procedure that accepts parameters and handles all the test logic. then I write a bunch of single line test procedures that call the other procedure passing in the appropriate parameters. There are a few examples for this in the test cases for tSQLt itself. This has few disadvantages over truly parameterized tests, but one big advantage: You can give each one a truly meaningful name that will make hunting down issues a lot simpler. (True parameterized tests are on the backlog, but they are not the highest priority, so it might be a while for them to make it.)

As a side note, I strongly advise against autogenerating tests or even parameters for tests, as that usually leads to higher maintenance costs. As the goal of testing is to reduce the cost of maintaining your codebase, that is counterproductive. I've seen a lot of unit testing adoption projects fail because of that very reason.

And because you mentioned extension points, at this time the only extension point is for the final result of an execution of tSQLt to be formatted. (tSQLt.SetTestResultFormatter)
